version: 1

jobs:
  py3test:
    working_directory: ~/megnet
    docker:
      - image: materialsvirtuallab/circle-ci-pmg-py3:0.0.2
    steps:
      - checkout
      - run:
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda info -a
            conda create -q -n test-environment python=3.6 numpy scipy matplotlib sympy cython tensorflow keras
            source activate test-environment
            conda update --quiet numpy scipy matplotlib sympy cython tensorflow keras
            pip install --quiet --ignore-installed -r requirements.txt -r requirements-ci.txt
            pip install tensorflow --upgrade
      - run:
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            source activate test-environment
            pip install --quiet -e .
            pytest --cov=megnet --cov-report html:coverage_reports --quiet megnet
            pycodestyle megnet
            coveralls
          no_output_timeout: 3600
      - store_artifacts:
          path: coverage_reports/
          destination: tr1
      - store_test_results:
          path: coverage_reports/

workflows:
  version: 2
  build_and_test:
    jobs:
      - py3test
